### ISSUE TITLE
What's wrong with this cda_query

### ISSUE THREAD

**Issue by capriosa** [contentful-labs/contentful_middleman#20]
What is wrong with this cda_query?
...
f.cda_query     = { content_type:'2wKXXXXXXXs4as', category: 'Markdown', include: 1 }
f.content_types = { post:'2wKXXXXXXXs4as' }
...

I get this error:
/Library/Ruby/Gems/2.0.0/gems/contentful-0.5.0/lib/contentful/client.rb:174:in `get': The query you sent was invalid. Probably a filter or ordering specification is not applicable to the type of a field. (Contentful::BadRequest)

**Comment by madtrick** [comment]
Hi @capriosa,

You are getting that error because you are using an unsupported filter parameters: `category`. Please take a look a the [documentation](https://www.contentful.com/developers/documentation/content-delivery-api/#search-filter) to find which are the supported filter parameters.

I guess that on this case you will want to do something like:

```ruby
f.cda_query = { content_type:'2wKXXXXXXXs4as', 'fields.category': 'Markdown', include: 1 }
f.content_types = { post:'2wKXXXXXXXs4as' }
```

**Comment by capriosa** [comment]
For a normal textfield like "title" this does the trick:
f.cda_query     = { content_type:'2wKn6yEnZewu2SCCkus4as', 'fields.title[match]' => 'Markdown',include:1}
Thanks
