### ISSUE TITLE
How to submit form data from middleman page to contentful

### ISSUE THREAD

**Issue by vishu099** [contentful-labs/contentful_middleman#37]
I have created a form page in my middleman and I would like to submit the form data and store it into the contentful content type. Is there any way I can achieve this ?

**Comment by neonichu** [comment]
Since middleman generates a static site, this isn't directly possible. However, you can probably build a solution using our Content Management API: <https://www.contentful.com/developers/documentation/content-management-api/#libraries>
Keep in mind that Contentful is not meant to store individual user data, though.
